### ISSUE TITLE
crash on ARC 066 E

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/template-generator#13]
``` console
$ pip3 show online-judge-template-generator | grep Version      
Version: 4.1.1

$ oj-template https://atcoder.jp/contests/arc066/tasks/arc066_c
INFO:onlinejudge._implementation.logging:[x] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
INFO:onlinejudge._implementation.logging:[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/arc066/tasks/arc066_c'): https://atcoder.jp/contests/arc066/tasks/arc066_c
INFO:onlinejudge._implementation.logging:[x] GET: https://atcoder.jp/contests/arc066/tasks/arc066_c
INFO:onlinejudge._implementation.logging:[x] 200 OK
INFO:onlinejudge._implementation.logging:[x] save cookie to: /home/user/.local/share/online-judge-tools/cookie.jar
ERROR:onlinejudge_template.analyzer.combined:output analyzer failed: 
Traceback (most recent call last):
  File "/home/user/.local/bin/oj-template", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/main.py", line 36, in main
    analyzed = onlinejudge_template.analyzer.combined.run(resources)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/analyzer/combined.py", line 47, in run
    input_format = onlinejudge_template.analyzer.parser.run(resources.input_format_string)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/analyzer/parser.py", line 451, in run
    parsed = parser.parse(lexer=lexer)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge_template/analyzer/parser.py", line 212, in p_items
    p[0] = SequenceParserNode(items=[dots] + p[2].items, **loc(p))
AttributeError: 'str' object has no attribute 'items'
```

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr"><a href="https://twitter.com/kimiyuki_u?ref_src=twsrc%5Etfw">@kimiyuki_u</a> <br>Online Judge Template Generatorにいつもお世話になってます バグ(?)報告です<a href="https://t.co/GVLkwTRaNx">https://t.co/GVLkwTRaNx</a><br>この問題でtemplate生成に失敗するようです</p>&mdash; こるとん (@kyort0n) <a href="https://twitter.com/kyort0n/status/1265663734862643202?ref_src=twsrc%5Etfw">May 27, 2020</a></blockquote>

**Comment by kmyk** [comment]
`A_1 op_1 A_2 ... op_{n-1} A_n` から `REP (i, n - 1) { read(A_i) ; read(op_i) } ; read(A_n)` を解析するのは無理すぎる (せめて `A_1 op_1 A_2 op_2 ... A_{n-1} op_{n-1} A_n` とかであってほしい) けど、それ以前のところで落ちててだめ

**Comment by kmyk** [comment]
この行が原因。単純な番号の間違いだけど、Python が動的型かつ yacc が動的生成なので mypy でも落とせなかった

https://github.com/online-judge-tools/template-generator/blob/256105b672a03cd71812eeefda99ba157fb0f64c/onlinejudge_template/analyzer/parser.py#L212
