### ISSUE TITLE
The default template `generate.py` has syntax error when string variables exsit in input

### ISSUE THREAD

**Issue by jellc** [online-judge-tools/template-generator#55]
```shell
oj-template -t generate.py https://atcoder.jp/contests/abc166/tasks/abc166_a
```
の生成コードが syntax error となっているようです。文字列が入力に与えられる他の問題でも同様でした。僕が python に不慣れなため、具体的な間違いの内容は分かりませんでした。。

**Comment by kmyk** [comment]
## ログ

``` console
$ oj-template -t generate.py https://atcoder.jp/contests/abc166/tasks/abc166_a > generate.py
INFO:onlinejudge.dispatch:problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/abc166/tasks/abc166_a'): https://atcoder.jp/contests/abc166/tasks/abc166_a
INFO:onlinejudge.utils:load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
INFO:onlinejudge.dispatch:problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/abc166/tasks/abc166_a'): https://atcoder.jp/contests/abc166/tasks/abc166_a
INFO:onlinejudge._implementation.utils:network: GET: https://atcoder.jp/contests/abc166/tasks/abc166_a
INFO:onlinejudge._implementation.utils:network: 200 OK
INFO:onlinejudge.utils:save cookie to: /home/user/.local/share/online-judge-tools/cookie.jar
ERROR:onlinejudge_template.analyzer.combined:output analyzer failed: 
INFO:onlinejudge_template.generator._main:use template file: /home/user/GitHub/online-judge-template-generator/onlinejudge_template_resources/template/generate.py
INFO:onlinejudge_template.generator.hook:execute filter command: $ yapf --style '{BASED_ON_STYLE: google, COLUMN_LIMIT: 9999}'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=10, value=']', context=('', (7, 73))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=10, value=']', context=('', (7, 73))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/yapf", line 8, in <module>
    sys.exit(run_main())
  File "/home/user/.local/lib/python3.6/site-packages/yapf/__init__.py", line 335, in run_main
    sys.exit(main(sys.argv))
  File "/home/user/.local/lib/python3.6/site-packages/yapf/__init__.py", line 194, in main
    verify=args.verify)
  File "/home/user/.local/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 129, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/user/.local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/user/.local/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 7
    S = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
                                                                         ^
SyntaxError: invalid syntax
ERROR:onlinejudge_template.generator.hook:Command '['yapf', '--style', '{BASED_ON_STYLE: google, COLUMN_LIMIT: 9999}']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/generator/hook.py", line 28, in _execute_hook
    return subprocess.check_output(data['hook'], input=rendered, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['yapf', '--style', '{BASED_ON_STYLE: google, COLUMN_LIMIT: 9999}']' returned non-zero exit status 1.

$ cat generate.py 
Traceback (most recent call last):
  File "/home/user/GitHub/online-judge-template-generator/onlinejudge_template/generator/hook.py", line 28, in _execute_hook
    return subprocess.check_output(data['hook'], input=rendered, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['yapf', '--style', '{BASED_ON_STYLE: google, COLUMN_LIMIT: 9999}']' returned non-zero exit status 1.


Generated code (before processed by the filter):
#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.7.0 (https://github.com/online-judge-tools/template-generator)
def main():
    S = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
    print(S)

if __name__ == "__main__":
    main()

$ vim generate.py 

$ cat generate.py
#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.7.0 (https://github.com/online-judge-tools/template-generator)
def main():
    S = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
    print(S)

if __name__ == "__main__":
    main()

$ python3 generate.py
  File "generate.py", line 7
    S = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
                                                                         ^
SyntaxError: invalid syntax
```

**Comment by kmyk** [comment]
@jellc 報告ありがとう。修正しました
